services:
  postgres:
    image: postgres:15
    container_name: asada_db
    environment:
      POSTGRES_USER: asada
      POSTGRES_PASSWORD: asada123
      POSTGRES_DB: calidad_agua
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: